# Generated by Django 5.1.1 on 2024-09-05 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_no', models.CharField(max_length=16, unique=True)),
                ('origin_country_id', models.CharField(max_length=2)),
                ('destination_country_id', models.CharField(max_length=2)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_slug', models.SlugField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['tracking_no'], name='generate_tn_trackin_879e34_idx')],
            },
        ),
    ]
